### ISSUE TITLE
Disable "Share on Pixelfed" per default

### ISSUE THREAD

**Issue by johegl** [janboddez/share-on-pixelfed#6]
I love this plugin! It works really nicely.

The only problem of sorts I have is that all the old posts now have the "share on pixelfed" flag set. When I now go back to one and - say - fix a typo, it suddenly gets shared as a new post on Pixelfed when I save ("update") it. I can already see myself accidentally sharing to Pixelfed XD For now I might run through the database once to set the flag to disabled somehow. And then try to remember to check that sharing option.

Maybe it would be nice to sort of make the sharing opt in, i.e. have the checkbox for "share on pixelfed" disabled by default and have the user explicitly mark it to share a post to Pixelfed?

Thx for the great work though! No matter what this plugin is a great help!

Cheers

**Comment by janboddez** [comment]
A-ha. You're right. I was of course assuming that you'd want to share _everything_ by default. (Think that's what most social sharing plugins do.)

But, yes, I can make this filterable so that you could easily make sharing "opt-in" with just one line of PHP. (I'd rather not add too many options to the UI, although I _could_ always add it as a setting later on.)

Like you mention, the only current workaround would be to explicitly add a `_share_on_pixelfed` custom field with a value of `(string) "0"` for all old posts.

**Comment by janboddez** [comment]
The latest version here on GitHub (I've yet to bump the version no. and release to WP.org!) now contains some code that allows the above.

Should you be interested in testing it (by overwriting the plugin's `includes/class-post-handler.php` with the one at https://github.com/janboddez/share-on-pixelfed/blob/master/includes/class-post-handler.php), just add the following to your theme's `functions.php` or a [must-use plugin](https://wordpress.org/support/article/must-use-plugins/):
```
add_filter( 'share_on_pixelfed_optin', '__return_true' );
```

**Comment by jglitsch** [comment]
This is great!

The filter solution should be enough, I think. It's great that you allow modifications that way and document them the way you do. I am modifying the output a little through your documented filters and now I am using this new filter too (after replacing the updated file).

I can now safely update any post without having to remember that I it might accidentally get shared (I have multiple categories of posts on my Wordpress site, some of which should not go to Pixelfed). I tried that on a handful of posts and it did not break anything. Sharing still works great too! So I'd say, my tests were successful :-)

Thank you for this awesome change and putting your time into this plugin at all! I've been looking for something like this for a while!

**Comment by johegl** [comment]
This is great!

The filter solution should be enough, I think. It's great that you allow modifications that way and document them the way you do. I am modifying the output a little through your documented filters and now I am using this new filter too (after replacing the updated file).

I can now safely update any post without having to remember that I it might accidentally get shared (I have multiple categories of posts on my Wordpress site, some of which should not go to Pixelfed). I tried that on a handful of posts and it did not break anything. Sharing still works great too! So I'd say, my tests were successful :-)

Thank you for this awesome change and putting your time into this plugin at all! I've been looking for something like this for a while!

**Comment by janboddez** [comment]
> The filter solution should be enough, I think.

I think so, too, but not everyone knows (even a little) PHP. :-)

> I have multiple categories, some of which should not go to Pixelfed.

Ooh, in that case, you might wanna also consider `apply_filters( 'share_on_pixelfed_enabled', $is_enabled, $post )`:

```
add_filter( 'share_on_pixelfed_enabled', function( $is_enabled, $post ) {

  if ( in_category( ['cat1', 'cat2', 'cat3'], $post ) ) { // An array of category slugs or IDs to check against.
    return false; // Don't ever share this post, regardless of its setting.
  }

  return $is_enabled; // The custom field (or "checkbox") value.
}, 10, 2 );
```

Turns out it isn't yet documented anywhere, dangit. Its Mastodon counterpart is, though: https://jan.boddez.net/wordpress/share-on-mastodon#share_on_mastodon_enabled (although apparently there I'm using the post ID rather than a post object).

Anyway, what this does (or should do) is prevent a post from being shared when it is published (or updated). Even if the checkbox is/was checked.

**Comment by johegl** [comment]
Oh no, what you did here is perfect for me. So, thx again :-)

> Turns out it isn't yet documented anywhere, dangit.
I read your mention of the Mastodon plugin and just adapted it for the Pixelfed plugin. It turned out that I could not decide which categories should be posted and which not though. So I did not use that particular filter ;-)
